### ISSUE TITLE
有关xml绘制图片的问题

### ISSUE THREAD

**Issue by ghost** [GcsSloop/Gank#12]
请问作者大大，drawerlayout上的抽屉logo比如ios Android之类的那些小图片，是你自己在xml里绘制的吗？还是有一些神奇的网站可以直接下载啊？
我在阿里的iconfont网站上下载的svg图片，放到AS里读不出来呀。。

**Comment by GcsSloop** [comment]
http://zheteng.me/android/2016/01/06/android-studio-vector-assets/

**Comment by ghost** [comment]
谢谢前辈指教，原来AS自带这些骚骚的logo

**Comment by GcsSloop** [comment]
(=ﾟωﾟ)ﾉ
